[
    {
    "import":"Color",
    "BLACK":"BLACK",
    "RED":"RED",
    "GREEN":"GREEN",
    "YELLOW":"YELLOW",
    "BLUE":"BLUE",
    "MAGENTA":"MAGENTA",
    "CYAN":"CYAN",
    "WHITE":"WHITE",
    "BOLD":"BOLD",
    "UNDERLINE":"UNDERLINE"
    }
]